services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_DB: rinhadb
      POSTGRES_PASSWORD: local_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
